module.exports.descriptors = [
    'Green',
    'Majestic',
    'Petrified',
    'Secret',
    'Sleepy',
    'Cozy',
    'Quaint',
    'Misty',
    'Rustic',
    'Bullfrog',
    'Wildlife',
    'Starry',
    'Ocean Side',
    'Sandy',
    'Rocky',
    'Grassy',
]

module.exports.places = [
    'Flats',
    'Village',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ferret Camp',
    'Back Country',
    'Hoe Down',
    'Boon Docks',
    'Lake Side',
    'Camp',
    'Bay',
    'Creek',
    'Sands',
    'Shores',
    'Hunt',
    'Weldonside',
    'Cliffs',
    'Hollow',
    'fields'
]